# Generated by Django 5.0.3 on 2025-11-17 15:43

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('quit', 'Quit'), ('retired', 'Retired'), ('deceased', 'Deceased')], default='active', max_length=20)),
                ('shutdown_date', models.DateField(blank=True, null=True)),
                ('shutdown_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('final_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
            ],
            options={
                'ordering': ('registration_number',),
            },
        ),
    ]
