# Generated by Django 5.0.3 on 2025-11-19 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('special', 'Special Savings'), ('fixed', 'Fixed Deposit'), ('death', 'Death Benefit Account')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('dividend', 'Dividend'), ('withdrawal', 'Withdrawal'), ('withdrawal_benefit', 'Withdrawal Benefit'), ('death_charge', 'Death Charge'), ('default_charge', 'Default Charge'), ('cash_receipt', 'Cash Receipt')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cash_dividends.savingsaccount')),
                ('related_account', models.ForeignKey(blank=True, help_text='For death benefits or charges applied to another account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='cash_dividends.savingsaccount')),
            ],
        ),
    ]
