# Generated by Django 5.0.3 on 2025-11-19 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='ReportCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('total_premium', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fixed_target_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shares_investment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('major_loan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('car_loan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('electronics_loan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('land_loan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('essential_commodities_loan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('education_loan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('emergency_loan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_loan_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.accountprofile')),
            ],
            options={
                'unique_together': {('account', 'period')},
            },
        ),
    ]
